### ISSUE TITLE
Status: incompatible

### ISSUE THREAD

**Issue by Aur0r4** [phanx-wow/Masque_SimpleSquare#1]
Hi,

just wanted to tell you that your skin is marked as "incompatible" in Masque settings, but for me it is still working. Maybe you want to update it...

Very nice looking skin btw :) thanks for that

![image](https://user-images.githubusercontent.com/28149249/80971371-f5a9dd00-8e1c-11ea-994e-6e441f9d6a51.png)

**Comment by StormFX** [comment]
I'm in the process of adjusting the compatibility status. Anything that uses Masque's API will be listed as compatible (Yellow). Anything with a `Masque_Version` of `70200` or higher will be listed in green.

Unrelated: Why is that showing Masque's info? Curious.

**Comment by Aur0r4** [comment]
Thanks for that information!
I can't tell you why it is showing wrong informations, I've downloaded it years ago at WoWInterface.com.

https://www.wowinterface.com/downloads/info9096-MasqueSimpleSquare.html

I've just seen that it is yellow now, so I will hit the close button. 👍
